#page title
page_title:

# App Info
ios_app_id:
ios_app_country:

appstore_link:
playstore_link: https://play.google.com/store/apps/details?id=com.juniorise.camgeo
presskit_download_link:

app_icon: https://play-lh.googleusercontent.com/Hs2oZc90_a5dZY-xJPFQ7ktP23TUnLy6kGESL_M6_j0rYtlyqIpBhr4ktSa_s-_FeHAw=s360-rw
app_name: CamGeo - ភូមិសាស្ត្រកម្ពុជា
app_price: Free
app_description: Discover places & geography around Cambodia 📝
whats_new: https://github.com/CSG6Project1/cambodia_geography_mobile/releases

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Juniorise
your_link: https://camgeo.juniorise.com
your_city: Phnom Penh
email_address: spooky@juniorise.com
facebook_username: camgeo.juniorise
instagram_username:
twitter_username:
github_username: juniorise
youtube_username:

features:
  - title: Geography
    description: Cover all geography at all 25 provinces in Cambodia. 
    fontawesome_icon_name: magic

  - title: Tourism Place
    description: Old temples with their detail & images
    fontawesome_icon_name: mobile

  - title: Restuarant
    description: Support local restaurants by promoting them in our application
    fontawesome_icon_name: play-circle

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: https://cdn.britannica.com/24/77424-050-4FF80B58/Angkor-Wat-Cambodia.jpg #
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#ffffff"
feature_icons_background_color: "#ce2b30"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
